/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlRouteImport } from './routes/control'
import { Route as EvaluatorsRouteImport } from './routes/evaluators'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MapRouteImport } from './routes/map'
import { Route as ScrutinyRouteImport } from './routes/scrutiny'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as VerifyRouteImport } from './routes/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluatorsRoute = EvaluatorsRouteImport.update({
  id: '/evaluators',
  path: '/evaluators',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrutinyRoute = ScrutinyRouteImport.update({
  id: '/scrutiny',
  path: '/scrutiny',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/evaluators': typeof EvaluatorsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/scrutiny': typeof ScrutinyRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/evaluators': typeof EvaluatorsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/scrutiny': typeof ScrutinyRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/evaluators': typeof EvaluatorsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/scrutiny': typeof ScrutinyRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/control'
    | '/evaluators'
    | '/login'
    | '/map'
    | '/scrutiny'
    | '/vault'
    | '/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/control'
    | '/evaluators'
    | '/login'
    | '/map'
    | '/scrutiny'
    | '/vault'
    | '/verify'
  id:
    | '__root__'
    | '/'
    | '/control'
    | '/evaluators'
    | '/login'
    | '/map'
    | '/scrutiny'
    | '/vault'
    | '/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlRoute: typeof ControlRoute
  EvaluatorsRoute: typeof EvaluatorsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  ScrutinyRoute: typeof ScrutinyRoute
  VaultRoute: typeof VaultRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluators': {
      id: '/evaluators'
      path: '/evaluators'
      fullPath: '/evaluators'
      preLoaderRoute: typeof EvaluatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrutiny': {
      id: '/scrutiny'
      path: '/scrutiny'
      fullPath: '/scrutiny'
      preLoaderRoute: typeof ScrutinyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlRoute: ControlRoute,
  EvaluatorsRoute: EvaluatorsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  ScrutinyRoute: ScrutinyRoute,
  VaultRoute: VaultRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
